name: bluex-env-print-test
version: '0.1'
summary: Print environment
description: |
  Print environment

grade: stable
confinement: strict

apps:
  env-print:
    command: env-print
  daemon1:
    command: env-print
    daemon: simple

parts:
  env-print-cmd:
    source: https://github.com/bluex-pl/env-print.git
    plugin: python
    requirements: requirements.txt
  
    
